global:
  scrape_interval: 5s
scrape_configs:
 
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'db'
    static_configs:
      - targets: ['mysqld-exporter:9104']
  - job_name : 'docker'    
    static_configs:
      - targets: ['172.17.0.1:9323'] 
  - job_name: 'cadvisor' 
    static_configs: 
      - targets: ['cadvisor:8080'] 
  - job_name: 'node_exporter'
    static_configs:
       - targets: ['192.168.0.13:9100']     
